### ISSUE TITLE
Vue.utils.warn break build process.

### ISSUE THREAD

**Issue by Fnxxxxo** [vueuse/vue-demi#214] opened 2023-02-16 07:13 UTC
I build a component repo with vue.2.7 and vue-demi.0.13.11. The dist artifact is wired with a NPE.
<img width="653" alt="lQLPJxBSESCyRRxozQUZsK_10SXmQKrdA-fd554A-QA_1305_104" src="https://user-images.githubusercontent.com/37140132/219293117-da007645-709b-4dcb-9fd3-7af46057d07c.png">
It crushes the building process in my vue.3.0 project. Maybe an issue caused by #192 ?

**Comment by vuesomedev** [comment] 2023-02-24 11:09
Coming from `vuelidate`, the newest version crashes with the above error when using Vue 3 without compatibility mode.

**Comment by brunomperes** [comment] 2023-03-22 15:47
I think this is related to it using a .mjs extension https://github.com/webpack/webpack/issues/16000#issuecomment-1169821843 and the fix is basically what is applied for .cjs [here](https://github.com/vueuse/vue-demi/commit/1147a815846ffb906225d30ebee01a486012f4e3)

**Comment by antfu** [comment] 2023-03-22 15:48
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-22 15:48 UTC
