### ISSUE TITLE
The requested module 'vue-demi' does not provide an export named 'computed'

### ISSUE THREAD

**Issue by xupeng-faker** [vueuse/vue-demi#238] opened 2023-06-06 01:12 UTC
When I build with vitepress, get error

/node_modules/@vueuse/shared/index.mjs:1
import { shallowRef, watchEffect, readonly, unref, ref, isVue3, version, watch, customRef, getCurrentScope, onScopeDispose, effectScope, provide, inject, isRef, computed, reactive, toRefs as toRefs$1, toRef, isVue2, set as set$1, getCurrentInstance, onBeforeMount, nextTick, onBeforeUnmount, onMounted, onUnmounted, isReactive } from 'vue-demi';
                                                                                                                                                                 ^^^^^^^^
SyntaxError: The requested module 'vue-demi' does not provide an export named 'computed'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:121:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:171:5)

Remote
System : Linux *86
node : v16.1.0
npm: 8.0.0

but I don't have this problem on my local window system

local ：
system ： window10
node：14.19.1
npm: 6.14.16

**Comment by agulado** [comment] 2023-06-09 07:08
I have a same question on centos 7, and don't have it on my local macbookpro that os version is 13.3.1

**Comment by antfu** [comment] 2023-06-09 08:50
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-06-09 08:50 UTC

**Comment by agulado** [comment] 2023-06-12 10:56
> I have a same question on centos 7, and don't have it on my local macbookpro that os version is 13.3.1

I have solved my question, the reason is the version of my docker is 6.x, and it has become normal when I upgrade npm to 8.x.
