### ISSUE TITLE
Error with vite 4

### ISSUE THREAD

**Issue by mikob** [vueuse/vue-demi#221] opened 2023-04-14 20:20 UTC
I'm using Astro 2.3.0 which uses vite 4 and getting this error on the latest 0.14.0 demi:
```
instantiating module /node_modules/.pnpm/astro@2.3.0/node_modules/astro/dist/runtime/server/render/index.js
instantiating module /node_modules/.pnpm/astro@2.3.0/node_modules/astro/dist/runtime/server/jsx.js
instantiating module /@fs/home/mikob/scratchspace/oh-vue-icons/node_modules/vue-demi/lib/index.mjs
2:17:00 PM [vite] Error when evaluating SSR module /@fs/home/mikob/scratchspace/oh-vue-icons/node_modules/vue-demi/lib/index.mjs:

2:17:00 PM [vite] Error when evaluating SSR module /@fs/home/mikob/scratchspace/oh-vue-icons/package/dist/index.mjs:

2:17:00 PM [vite] Error when evaluating SSR module /src/vue_app.ts:

2:17:00 PM [vite] Error when evaluating SSR module virtual:@astrojs/vue/app:

2:17:00 PM [vite] Error when evaluating SSR module @astrojs/vue/server.js:

 error   Cannot redefine property: __esModule
  File:
    /home/mikob/workspace/hairgen.ai/frontend/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:53983:24
  Code:
    53982 |             if (key !== 'default') {
    > 53983 |                 Object.defineProperty(ssrModule, key, {
            |                        ^
      53984 |                     enumerable: true,
      53985 |                     configurable: true,
      53986 |                     get() {
  Stacktrace:
TypeError: Cannot redefine property: __esModule
    at Function.defineProperty (<anonymous>)
    at ssrExportAll (file:///home/mikob/workspace/hairgen.ai/frontend/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:53983:24)
    at eval (/home/mikob/scratchspace/oh-vue-icons/node_modules/vue-demi/lib/index.mjs:33:1)
    at async instantiateModule (file:///home/mikob/workspace/hairgen.ai/frontend/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:53997:9)
```

Astro config:
```
export default defineConfig({
    vite: {
        ssr: {
            external: ["vue3-picture-swipe"],
            noExternal: ["oh-vue-icons"],
        },
        optimizeDeps: {
            exclude: ["oh-vue-icons/icons"],
        },
    },
    integrations: [
        vue({
            appEntrypoint: "/src/vue_app",
        }),
   ]
});

**Comment by mikob** [comment] 2023-04-14 20:29
I've also tried with this in the config:
```
        optimizeDeps: {
            exclude: ["oh-vue-icons/icons", "vue-demi"],
        },
```
And in the oh-vue-icons library:
```
   optimizeDeps: {
            exclude: ["vue-demi"],
        },
```

**Comment by antfu** [comment] 2023-04-14 21:00
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-04-14 21:00 UTC

**Comment by mikob** [comment] 2023-04-15 00:34
Looks to have been a pnpm issue. 
Adding to .npmrc:
```
shamrefully-hoist=true
```
fixes it.
