### ISSUE TITLE
"isVue2 isVue3" there are differences in different environments

### ISSUE THREAD

**Issue by DDYMZL** [vueuse/vue-demi#218] opened 2023-03-02 03:48 UTC
When I debug the plug-in locally(use: npm link)

`import { isVue2, isVue3 } from "vue-demi";`

`console.log(isVue2, isVue3) // false true`

When I publish

`import { isVue2, isVue3 } from "vue-demi";`

`console.log(isVue2, isVue3) // true false `

they are all in vue2 project

**Comment by antfu** [comment] 2023-03-06 05:59
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-06 05:59 UTC
