### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'warn')

### ISSUE THREAD

**Issue by hrj904064990** [vueuse/vue-demi#202] opened 2022-10-28 03:57 UTC
I updated nodejs to 16.0 and then re-installed the dependency packages and the project won't open
vue2 + pinia
![image](https://user-images.githubusercontent.com/44388472/198499135-9bd5a5eb-2802-4dc7-89cf-2e0dde0882cc.png)

**Comment by yangxyo** [comment] 2023-01-03 07:13
+1

**Comment by liam61** [comment] 2023-02-06 10:22
same error, anyone can help? plz

**Comment by doubleaxe** [comment] 2023-04-18 13:56
See this issue: https://github.com/vueuse/vue-demi/issues/192
This is broken in old webpack build, they fixed it, but only inside `index.cjs`, not inside `index.mjs`.
One solution is to use alias to compile fixed `index.cjs` instead of broken `index.mjs` until it get fix too.

```
        resolve: {
            alias: {
                //TypeError: Cannot read properties of undefined (reading 'warn')
                //var warn = Vue.util.warn
                'vue-demi$': 'vue-demi/lib/index.cjs',
            },
        },
```

**Comment by antfu** [comment] 2023-04-18 15:55
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-04-18 15:55 UTC
