### ISSUE TITLE
Cannot find module /.output/server/node_modules/vue-demi/lib/index.cjs' in Nuxt 3

### ISSUE THREAD

**Issue by elzodxon** [vueuse/vue-demi#209] opened 2023-02-07 07:43 UTC
<img width="1262" alt="Screenshot 2023-02-07 at 12 33 58" src="https://user-images.githubusercontent.com/52325239/217182378-c6a432d7-acf3-4e9a-bee3-8736bd4f8e67.png">

I am having this issue in Nuxt 3 using vuelidat.e How can I resolve it? Should I upgrade or downgrade package.

**Comment by metalsm7** [comment] 2023-09-08 08:53
This may be a late answer, but I'm writing it down for anyone who might need it. In my case, I had the same error in @vuelidate/core, @vuelidate/validators 2.0.0 and after updating those packages, the error went away.

**Comment by antfu** [comment] 2023-09-08 09:14
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-08 09:14 UTC
