### ISSUE TITLE
hasInjectionContext bug

### ISSUE THREAD

**Issue by huluobotx** [vueuse/vue-demi#226] opened 2023-05-17 13:16 UTC
Uncaught SyntaxError: The requested module '/@fs/D:/client/node_modules/.pnpm/registry.npmmirror.com+vue-demi@0.14.1_vue@3.2.45/node_modules/vue-demi/lib/index.mjs?v=a8db8362' does not provide an export named 'hasInjectionContext' (at pinia.mjs:6:10)

**Comment by antfu** [comment] 2023-05-17 13:25
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-05-17 13:25 UTC
