### ISSUE TITLE
version switching error

### ISSUE THREAD

**Issue by vfvoedyyrd5105** [vueuse/vue-demi#220] opened 2023-04-14 02:21 UTC
execute npx vue-demi-switch 3 vue3

error :
> npx vue-demi-switch 3 vue3
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vue-demi-switch - Not found
npm ERR! 404 
npm ERR! 404  'vue-demi-switch@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

**Comment by antfu** [comment] 2023-04-14 07:45
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-04-14 07:45 UTC

**Comment by PixsaOJ** [comment] 2024-09-05 21:16
I get this time to time. Now i can not seem to pass this error.
