### ISSUE TITLE
when i want to switch to v2, there is a warning info and then get error 

### ISSUE THREAD

**Issue by Jinwan5290** [vueuse/vue-demi#165] opened 2022-06-21 08:59 UTC
<img width="787" alt="image" src="https://user-images.githubusercontent.com/49583674/174760533-7d3a60ff-aa72-484f-a238-f2ca406ab4c8.png">
this is my package.json
![image](https://user-images.githubusercontent.com/49583674/174760657-89e6d388-a125-4d8e-b2e1-d7374340f065.png)

**Comment by antfu** [comment] 2022-06-21 09:00
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-21 09:00 UTC
