### ISSUE TITLE
Incompatible when using App type in nuxt3

### ISSUE THREAD

**Issue by 18zili** [vueuse/vue-demi#211] opened 2023-02-08 10:32 UTC
nuxt3 `plugins/use.ts`

```js
import MyCode from 'my-code'

export default defineNuxtPlugin((nuxtApp) => {
  const myCode = new MyCode()
  nuxtApp.vueApp.use(myCode)
})
```

myCode
```js
import { App } from 'vue-demi';

export MyCode {
    install(app: App): void;
}
```

> error info ⬇️

```
Types of property 'install' are incompatible.
       Type '(app: App<any>) => void' is not assignable to type 'PluginInstallFunction'.
         The types of parameters 'app' and 'app' are incompatible.
```

**Comment by antfu** [comment] 2023-02-08 13:25
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-08 13:25 UTC
