### ISSUE TITLE
How we resolve dependency issue for ?

### ISSUE THREAD

**Issue by bhagvanp** [vueuse/vue-demi#243] opened 2023-09-01 11:43 UTC
This dependency was not found:
@vue/composition-api/dist/vue-composition-api.mjs in ./node_modules/@floating-ui/vue/node_modules/vue-demi/lib/index.mjs, ./node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs

"@vue/composition-api": "^1.7.1"
"@storefront-ui/vue": "^2.5.0"
"vue": "2.6.14"
"vue-server-renderer": "2.6.14"
"vue-template-compiler": "2.6.14"
"vue-demi": "^0.13.11"

**Comment by antfu** [comment] 2023-09-01 13:54
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-01 13:54 UTC
