### ISSUE TITLE
Cannot read properties of undefined (reading 'version')

### ISSUE THREAD

**Issue by v1talii-dev** [vueuse/vue-demi#124] opened 2022-01-11 09:56 UTC
I use [vue-echarts](https://github.com/ecomfe/vue-echarts) in my library, but when I connect the component, I see the following error:
![image](https://user-images.githubusercontent.com/12966923/148920587-dd3ee594-676d-4cad-8532-435083467f7e.png)

What could be the problem?

**Comment by kakajun** [comment] 2022-01-20 07:59
@v1talii-dev   maybe you can ask  vue-echarts, I used normal

**Comment by antfu** [comment] 2022-01-21 05:50
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-01-21 05:50 UTC
