### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by kaznache** [vueuse/vue-demi#129] opened 2022-01-31 10:13 UTC
Hi!
I'm trying to use Vue3 component inside Vue2 tool, but I face such error:

![image](https://user-images.githubusercontent.com/21216689/151773914-0bc9d089-9e26-4885-9530-b312db37c93a.png)

![image](https://user-images.githubusercontent.com/21216689/151774835-2a6fb419-b25b-4505-973e-ffd003442229.png)

I have a Vue3 project and export only TestComponent from there. This is a simple component that prints only text and expects one string prop. I built the project and copied built file to Vue2 project (because it's too long to publish it) and I'm trying to import Vue3 component there.

![image](https://user-images.githubusercontent.com/21216689/151775134-eb9e2269-5b8e-4e26-8173-2d5bd564c7d3.png)

In Vue3 project I use vue-demi and in Vue2 project I use composition api.

Do you have any thoughts how to fix that error?

**Comment by antfu** [comment] 2022-02-07 06:17
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-02-07 06:17 UTC
